version: "3"

services:
  app:
    build: .
    volumes:
      - static:/app/static
      - media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - pgdb
  pgdb:
    image: postgres
    env_file:
      - .env
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

volumes:
  pgdbdata: null
  media:
  static: