# Generated by Django 5.0.3 on 2024-03-08 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstablishmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('question_text', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='onboarding_forms.establishmenttype')),
            ],
        ),
    ]
