# Generated by Django 5.0.3 on 2024-03-08 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_forms', '0002_establishmentquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishmentquestion',
            name='title',
        ),
        migrations.AddField(
            model_name='establishmentquestion',
            name='establishment_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='onboarding_forms.establishmenttype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='establishmentquestion',
            name='question_text',
            field=models.CharField(max_length=255),
        ),
    ]
