# Generated by Django 5.0.3 on 2024-03-10 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_forms', '0003_remove_establishmentquestion_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding_forms.establishment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding_forms.establishmentquestion')),
            ],
        ),
    ]
