# Generated by Django 5.0.3 on 2024-03-10 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_forms', '0004_clientresponse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientResponse',
            new_name='ClientTypeResponse',
        ),
        migrations.RenameModel(
            old_name='EstablishmentQuestion',
            new_name='EstablishmentTypeQuestion',
        ),
        migrations.CreateModel(
            name='EstablishmentSubtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('establishment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='onboarding_forms.establishmenttype')),
            ],
        ),
        migrations.AddField(
            model_name='establishment',
            name='establishment_subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='onboarding_forms.establishmentsubtype'),
        ),
        migrations.CreateModel(
            name='EstablishmentSubtypeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('establishment_subtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='onboarding_forms.establishmentsubtype')),
            ],
        ),
        migrations.CreateModel(
            name='ClientSubtypeResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding_forms.establishment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding_forms.establishmentsubtypequestion')),
            ],
        ),
    ]
