# Generated by Django 5.0.3 on 2024-03-10 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_forms', '0005_rename_clientresponse_clienttyperesponse_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientTypeResponse',
            new_name='ClientResponse',
        ),
        migrations.RenameModel(
            old_name='EstablishmentTypeQuestion',
            new_name='EstablishmentQuestion',
        ),
        migrations.RemoveField(
            model_name='establishmentsubtype',
            name='establishment_type',
        ),
        migrations.RemoveField(
            model_name='establishmentsubtypequestion',
            name='establishment_subtype',
        ),
        migrations.RemoveField(
            model_name='establishment',
            name='establishment_subtype',
        ),
        migrations.DeleteModel(
            name='ClientSubtypeResponse',
        ),
        migrations.DeleteModel(
            name='EstablishmentSubtypeQuestion',
        ),
        migrations.DeleteModel(
            name='EstablishmentSubtype',
        ),
    ]
