# Generated by Django 5.0.3 on 2024-03-10 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_forms', '0006_rename_clienttyperesponse_clientresponse_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientresponse',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='establishment',
            options={'verbose_name': 'Заведение', 'verbose_name_plural': 'Заведения'},
        ),
        migrations.AlterModelOptions(
            name='establishmentquestion',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='establishmenttype',
            options={'verbose_name': 'Тип заведения', 'verbose_name_plural': 'Типы заведения'},
        ),
        migrations.AlterField(
            model_name='establishment',
            name='address',
            field=models.CharField(max_length=400, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='city',
            field=models.CharField(max_length=255, verbose_name='Страна и город'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='establishment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='onboarding_forms.establishmenttype', verbose_name='Тип заведения'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='is_new',
            field=models.BooleanField(verbose_name='Зто новое заведение'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название заведения'),
        ),
    ]
